### ISSUE TITLE
is it possible to hide live preview?

### ISSUE THREAD

**Issue by sibelius** [JReinhold/mdx-deck-live-code#10]

**Comment by JReinhold** [comment]
Not at the moment, but it could easily be built. Can you tell me about the use case? I'm a bit confused as to when you'd want that?

**Comment by sibelius** [comment]
this is my use case https://sibelius.github.io/functional-types-abstractions/#20

I just want to show the code snippet in a pretty way

**Comment by JReinhold** [comment]
Oh I see. If you're not planning on actually live editing the code, I'd recommend you take a look at https://github.com/pomber/code-surfer which is made for showing static code in a pretty way. (You can just set it to highlight all the lines, instead of just some of them)

If you're u want the editing feature, it might be better to just have a textarea with syntax-highlighting using highlight.js or similar. I think it's a bit too much to have all the transpiling and evaluation functionality this library offers, without actually using it.
